apiVersion: widgets.templates.krateo.io/v1beta1
kind: Flex
metadata:
  annotations:
    krateo.io/allowed-resources: derived
    krateo.io/nav-label: Pod sizing
    krateo.io/nav-order: '100'
    krateo.io/nav-path: /pb-v1-20261002-1
  name: page-pb-v1-20261002-1
  namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
spec:
  resourcesRefs:
    items:
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: page-pb-v1-20261002-1-header
        name: page-pb-v1-20261002-1-header
        namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
        resource: pageheaders
        verb: GET
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: pb-v1-20261002-1-verdicts
        name: pb-v1-20261002-1-verdicts
        namespace: krateo-system
        resource: piecharts
        verb: GET
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: pb-v1-20261002-1-pods
        name: pb-v1-20261002-1-pods
        namespace: krateo-system
        resource: tables
        verb: GET
  widgetData:
    allowedResources:
      - piecharts
      - tables
    gap: middle
    items:
      - resourceRefId: page-pb-v1-20261002-1-header
      - resourceRefId: pb-v1-20261002-1-verdicts
      - resourceRefId: pb-v1-20261002-1-pods
    vertical: true
